name: Build OpenWrt Firwmare

on:
  # push:
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/openwrt/openwrt.git
  RELEASE_TAG: v24.10.0
  ARGON_THEME_RELEASE_TAG: v2.3.2
  TZ: Asia/Shanghai

jobs:
  build_openwrt_firmware:
    name: Build OpenWrt Firmware
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        
    - name: Clone source code
      working-directory: /workdir
      run: |
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        cd openwrt

    - name: Cache
      uses: actions/cache@v3.4.3
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: ${{ github.workspace }}/openwrt

    - name: Choose a release
      run: |
        cd openwrt
        git pull
        git branch -a
        git tag
        git checkout $RELEASE_TAG

    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a -f

    - name: Load custom configuration
      run: |
        [ -e $CONFIG_DIFF_FILE ] && mv $CONFIG_DIFF_FILE openwrt/.config
        TODAY=$(date +%Y-%m-%d)
        sh -c "sed -i -e 's/CONFIG_VERSION_NUMBER=.*/CONFIG_VERSION_NUMBER=\"${TODAY}\"/' openwrt/.config"

    - name: Generate configuration file
      run: cd openwrt && make defconfig

    - name: Download package
      id: package
      run: |
        cd openwrt
        make download -j16
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Download theme
      id: theme
      run: |
        cd openwrt/package
        [ -d luci-theme-argon ] && rm -rf luci-theme-argon
        git clone https://github.com/jerrykuku/luci-theme-argon.git
        cd luci-theme-argon
        git branch -a
        git tag
        git checkout $ARGON_THEME_RELEASE_TAG

    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt
        echo -e "compile"
        make -j$(nproc) || make -j1 V=s
        echo "======================="
        echo "Space usage:"
        echo "======================="
        df -h
        echo "======================="
        echo "::set-output name=status::success"
        tdev=$(grep "CONFIG_TARGET_PROFILE" .config | awk -F= '{print $2}' | tr -d '"')
        DEVICE_NAME=${tdev##DEVICE_}
        FILE_DATE=_$(date +"%Y%m%d%H%M")
        GIT_REV=_$(git rev-parse --short HEAD)
        echo "DEVICE_NAME=${DEVICE_NAME}" >> $GITHUB_ENV
        echo "FILE_DATE=${FILE_DATE}" >> $GITHUB_ENV
        echo "GIT_REV=${GIT_REV}" >> $GITHUB_ENV
        echo "RELEASE_NAME=OpenWrt_firmware_${DEVICE_NAME}${GIT_REV}${FILE_DATE}.tar.gz" >> $GITHUB_ENV

    - name: Check space usage
      run: |
        df -hT
        echo "tree directory ....."
        cd openwrt
        tree -L 2 -d

    - name: Prepare artifact
      run: |
        TEMP=$(date +"OpenWrt_${{ env.DEVICE_NAME }}_%Y%m%d_%H%M%S_")$(git rev-parse --short HEAD)
        echo "RELEASE_TAG=$TEMP" >> $GITHUB_ENV
        tar -cvzf ${{ github.workspace }}/${{env.RELEASE_NAME}} openwrt/bin/targets/ramips/mt7620/* --owner=0 --group=0
        rm -rf $(find openwrt/bin/targets/ -type d -name "packages")

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.RELEASE_NAME }}
        path: ${{ github.workspace }}/${{env.RELEASE_NAME}}

    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
        echo "OpenWRT firmware ${{env.RELEASE_NAME}}" > openwrt-release.txt
        echo "::set-output name=status::success"

    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: openwrt-firmware
        body_path: openwrt-release.txt
        files: ${{ github.workspace }}/${{env.RELEASE_NAME}}

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      if: steps.tag.outputs.status == 'success'
      with:
        keep_latest: 6
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

